### ISSUE TITLE
Screenshot feature does not work in many websites

### ISSUE THREAD

**Issue by jonrandy** [kabuspl/to-google-lens#2]
It appears that the screenshot feature does not work on many websites. The wrong part of the screen is sent. Maybe you could try using this library: https://html2canvas.hertzen.com/ - it seems to work really well on all sites I've tried it on

Great extension by the way! Super useful

**Comment by kabuspl** [comment]
Do you have display scale set to a value other than 100% or do you have these websites zoomed? If so, I am already working on a fix for this problem. If not, can you specify on which websites the problem occurs?

**Comment by jonrandy** [comment]
I don't have the sites zoomed, and the problem occurs on most websites I have tried

**Comment by jonrandy** [comment]
This was what happened when I tried to screenshot the Github logo from this page:
<img width="1667" alt="image" src="https://user-images.githubusercontent.com/1510194/172369499-f8aa463b-f6ca-4852-a432-a0c5d4cd275b.png">

**Comment by jonrandy** [comment]
A video showing the behaviour:

https://user-images.githubusercontent.com/1510194/172370820-196e9423-32cc-4e28-a1d3-c65b05829ad3.mp4

**Comment by kabuspl** [comment]
From the screenshot and video I can see that you are using display scaling in operating system. I'm uploading new version with a fix. Thanks for report and please let me know if issue persists after the update.

**Comment by jonrandy** [comment]
Ah, it might be because of the retina screen on the Mac? I'll try it on my Ubuntu machine also... That's much lower res

**Comment by kabuspl** [comment]
Yes it's beacuse of retina. In the new version it should work. It's already published on addons.mozilla.org so you can go to about:addons, click on the gear icon and check for updates.
