### ISSUE TITLE
Cannot send anything to google lens Infinite spinner. Also the selection curor is invisible on some sites.

### ISSUE THREAD

**Issue by mzso** [kabuspl/to-google-lens#6]
I guess the mean functionality plainly just broke, probably by a change from google. Never goes beyond the "Uploading image..." message.

Also selection can be rather annoying because, the cursor becomes invisible. Perplexingly on pages with white backgrounds, which is the most common appearance...
Random example: https://floravita.superwebaruhaz.hu/

**Comment by kabuspl** [comment]
Fixed. I didn't notice the invisible cursor on white backgrounds because I use dark mode. Thanks for the report!

**Comment by mzso** [comment]
[**@kabuspl**](https://github.com/kabuspl) commented on [Sep 28, 2023, 4:34 PM GMT+2](https://github.com/kabuspl/to-google-lens/issues/6#issuecomment-1739381173 "2023-09-28T14:34:26Z - Replied by Github Reply Comments"):
> Fixed. I didn't notice the invisible cursor on white backgrounds because I use dark mode. Thanks for the report!
> 
> _Originally posted by @kabuspl in https://github.com/kabuspl/to-google-lens/issues/6#issuecomment-1739381173_

Great. I can verify that it works now.

I wonder what you mean by dark mode though? My OS and FF instance does use dark theme as well. But light webpages are light of course.

**Comment by mzso** [comment]
However I observe some submissings getting stuck uploading. Potentially infinitely.
[This submission](https://lens.google.com/search?ep=ccm&p=AbrfA8qcxMJd4ECVzMuukyStA0XZ8omiXbgoD1-k3FgOaGOM6-J_lAxHWAxg393JfixE3ibkihx93aqT-Qa7hnVPNu-Kyk9rWCFJXlBMfjc63v6HZJWaAfkkRILdbW9oKQEpvDjhPP8Wj1dWPCTdkaEWA0BaJdmj-ybbwvE3-pRsRhQCyzZFBHRVxknxK1Io2wXEm9SFLFuKzk4I6iNG-kXr2SoD-CKMLC92_VuMVamI7kxXrsrhUUdmikcQ4p7td3A8GR983-WSrMv304nGa2labW6HYwcbyALlRd9V66vDb6EmU4o4JOeE#lns=W251bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsIkVrY0tKR1ptWm1RMVpXSXhMV015TXpFdE5HWXhZeTFpTmpJeUxUUTFPREEyT0RZMFpqSmxOQklmY3psblgyMXZjSE13YmpoVlRVbG5SM0JuU1V4dVVEQkpkMnByUW5Kb1p3PT0iXQ==) (I don't know if it appears appropriately) got stock for a minute or so  (with an almost itentical submission) until a I searched for a smaller image. <del>Trying it a third time it got stock forever apparently.</del> For the [third time](https://lens.google.com/search?ep=ccm&p=AbrfA8phn3aBEMqEVoRA1HRVUrJl0vRqrPF6BrjRdfBz3-WX_hR50Ky-vUnn99IxRsS0XdG3QtbGZOV0BnZnxMQXGA4fB4l4cvWSpUuUq2jKnNPi8QdwDGgxelKxqrFy-j3PlRq9WZZqkSpuApxFu56kQAuHuYqpXPYY-FDseeMoQuTIppU7zaYAAnzqSKqPEE6FRNo-V7R6x1qpbSc83XMQZTjNQfQxCWK6U2xdN7EeVMYFrGvH6i-PIrFCWA_-tcMkH2OwpOY7y8RSU5NkAy6J87FTSaHCQLPyjZHA-uPBdcL-T2yzkazM#lns=W251bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsIkVrY0tKR0ZsWm1JNFpHVTFMV1k0WW1JdE5HWXlOeTA1TkRJNUxXVTBObVkxWVRnM01qVmlaQklmZHprMmVuUXlNR1ZYTUc5UlRVbG5SM0JuU1V4dVVERnZkM0JaUW5Kb1p3PT0iXQ==) it got stuck for several minutes. 4-7 minutes, until I almost got finished typing this comment. I tried refreshing a couple times during the wait, but it had no effect.

It's a mere screenshot of [this video](https://youtu.be/7DmAymNHxus?si=jpGENa45bl-gBEkF&t=625).

**Comment by kabuspl** [comment]
> [**@kabuspl**](https://github.com/kabuspl) commented on [Sep 28, 2023, 4:34 PM GMT+2](https://github.com/kabuspl/to-google-lens/issues/6#issuecomment-1739381173):
> 
> > Fixed. I didn't notice the invisible cursor on white backgrounds because I use dark mode. Thanks for the report!
> > _Originally posted by @kabuspl in [#6 (comment)](https://github.com/kabuspl/to-google-lens/issues/6#issuecomment-1739381173)_
> 
> Great. I can verify that it works now.
> 
> I wonder what you mean by dark mode though? My OS and FF instance does use dark theme as well. But light webpages are light of course.

I have DarkReader extension that turns all light websites dark.

**Comment by kabuspl** [comment]
> However I observe some submissings getting stuck uploading. Potentially infinitely. [This submission](https://lens.google.com/search?ep=ccm&p=AbrfA8qcxMJd4ECVzMuukyStA0XZ8omiXbgoD1-k3FgOaGOM6-J_lAxHWAxg393JfixE3ibkihx93aqT-Qa7hnVPNu-Kyk9rWCFJXlBMfjc63v6HZJWaAfkkRILdbW9oKQEpvDjhPP8Wj1dWPCTdkaEWA0BaJdmj-ybbwvE3-pRsRhQCyzZFBHRVxknxK1Io2wXEm9SFLFuKzk4I6iNG-kXr2SoD-CKMLC92_VuMVamI7kxXrsrhUUdmikcQ4p7td3A8GR983-WSrMv304nGa2labW6HYwcbyALlRd9V66vDb6EmU4o4JOeE#lns=W251bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsIkVrY0tKR1ptWm1RMVpXSXhMV015TXpFdE5HWXhZeTFpTmpJeUxUUTFPREEyT0RZMFpqSmxOQklmY3psblgyMXZjSE13YmpoVlRVbG5SM0JuU1V4dVVEQkpkMnByUW5Kb1p3PT0iXQ==) (I don't know if it appears appropriately) got stock for a minute or so (with an almost itentical submission) until a I searched for a smaller image. ~Trying it a third time it got stock forever apparently.~ For the [third time](https://lens.google.com/search?ep=ccm&p=AbrfA8phn3aBEMqEVoRA1HRVUrJl0vRqrPF6BrjRdfBz3-WX_hR50Ky-vUnn99IxRsS0XdG3QtbGZOV0BnZnxMQXGA4fB4l4cvWSpUuUq2jKnNPi8QdwDGgxelKxqrFy-j3PlRq9WZZqkSpuApxFu56kQAuHuYqpXPYY-FDseeMoQuTIppU7zaYAAnzqSKqPEE6FRNo-V7R6x1qpbSc83XMQZTjNQfQxCWK6U2xdN7EeVMYFrGvH6i-PIrFCWA_-tcMkH2OwpOY7y8RSU5NkAy6J87FTSaHCQLPyjZHA-uPBdcL-T2yzkazM#lns=W251bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsIkVrY0tKR0ZsWm1JNFpHVTFMV1k0WW1JdE5HWXlOeTA1TkRJNUxXVTBObVkxWVRnM01qVmlaQklmZHprMmVuUXlNR1ZYTUc5UlRVbG5SM0JuU1V4dVVERnZkM0JaUW5Kb1p3PT0iXQ==) it got stuck for several minutes. 4-7 minutes, until I almost got finished typing this comment. I tried refreshing a couple times during the wait, but it had no effect.
> 
> It's a mere screenshot of [this video](https://youtu.be/7DmAymNHxus?si=jpGENa45bl-gBEkF&t=625).

I will take a look at it. I was able to reproduce it.

**Comment by mzso** [comment]
This is still very common. Often it gets stuck on loading.
Sometimes it gets unstuck if I search for another screenshot. And both are sent simultaneously. (usually about the same thing)

**Comment by kabuspl** [comment]
I found a way to fix this. For some reason, Google's server sometimes has a problem with PNG files sent by this extension. I changed the code to send WEBP files instead and now it always works.
