### ISSUE TITLE
error: No results found for the selected area

### ISSUE THREAD

**Issue by josef821** [kabuspl/to-google-lens#7]
i tested your plugin. for image larger than 2000 it show error on google lens:
"No results found for the selected area"

check and download image:
https://imgur.com/a/d63BuCv

upload this image manually in google lens it work's but your plugin will show "no results error".

**Comment by kabuspl** [comment]
Works for me
![obraz](https://github.com/kabuspl/to-google-lens/assets/59837830/3a07dd8c-67ca-4b7a-b662-fc6bfba12e79)
