### ISSUE TITLE
Background tab

### ISSUE THREAD

**Issue by harryray33** [kabuspl/to-google-lens#8]
Would it be possible to add an option to open in a background tab, rather than switching to the tab?
Thanks

**Comment by kabuspl** [comment]
Thanks for the suggestion, I'll work on it.

**Comment by harryray33** [comment]
Any progress on this please?

Thanks.

**Comment by harryray33** [comment]
Is there a work around so that I can open this in a background tab?
Thanks.

**Comment by kabuspl** [comment]
I've added option in the latest version. You can set it here:
![image](https://github.com/kabuspl/to-google-lens/assets/59837830/1d46ab87-424a-467c-a54a-8bd43c0d088e)
If you don't have it update extension manually here:
![image](https://github.com/kabuspl/to-google-lens/assets/59837830/b3f50522-15e8-4443-8d97-0dc795ea50fb)

**Comment by harryray33** [comment]
That's brilliant, thanks, so much better...

Not important, but would it be possible that, when it opens in other tab, it doesn't load straight away, but waits until I click on the tab?

**Comment by kabuspl** [comment]
Done. I've uploaded the update to AMO and it's now awaiting approval. Should be available in a few minutes.

**Comment by kabuspl** [comment]
It's available as an option in the same location as the open in background feature

**Comment by harryray33** [comment]
Thanks again...This is such a useful extension.
Do you have any plans to write a similar extension for Bing and Yandex (I don't use Yandex, but it gives good results on image searches)
